language: c
sudo: required
services: docker
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script:
  - bash -ex .travis-docker.sh
env:
  global:
    - OCAML_VERSION=4.07
    - PACKAGE=xen-api-sdk
    - PINS="xen-api-sdk:."
    - DISTRO="debian-stable"
    - TESTS=false
    - INSTALL=false
    - BASE_REMOTE="https://github.com/xapi-project/xs-opam.git"
